default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASS'] %>

development:
  <<: *default
  database: pea_dev

test:
  <<: *default
  database: pea_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: 10
  database: pea_prod
