default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  username: root
  password: root

development:
  <<: *default
  database: peatio_development

test:
  <<: *default
  database: peatio_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: 10
  database: peatio_production
