- id: 200
  currency: btc
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 400
  currency: uah
  sort_order: 2
- id: 600
  currency: xrp
  sort_order: 3
  min_confirm: 1
  max_confirm: 3
- id: 800
  currency: bch
  sort_order: 3
  min_confirm: 1
  max_confirm: 3
- id: 1000
  currency: ltc
  sort_order: 3
  min_confirm: 1
  max_confirm: 3
- id: 1200
  currency: dashd
  sort_order: 3
  min_confirm: 1
  max_confirm: 3
- id: 1400
  currency: ethd
  sort_order: 3
  min_confirm: 1
  max_confirm: 3
- id: 20000
  currency: btcd
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 60000
  currency: xrpd
  sort_order: 3
  min_confirm: 1
  max_confirm: 3
- id: 80000
  currency: bchd
  sort_order: 3
  min_confirm: 1
  max_confirm: 3
- id: 100000
  currency: ltcd
  sort_order: 3
  min_confirm: 1
  max_confirm: 3