- id: 200
  currency: btc
  fixed: 8
  fee: 0.0005
  inuse: true
- id: 400
  currency: uah
  fixed: 2
  fee_max: 0
  min: 100
  max: 50000
  fee: 0.003
  proportion: true
  inuse: true
- id: 600
  currency: xrp
  fixed: 3
  fee: 0.0009
  inuse: true
- id: 800
  currency: bch
  fixed: 8
  fee: 0.0005
  inuse: true
- id: 1000
  currency: ltc
  fixed: 8
  fee: 0.0005
  inuse: true
- id: 1200
  currency: dashd
  fixed: 8
  fee: 0.0005
  inuse: true
- id: 1400
  currency: ethd
  fixed: 8
  fee: 0.0005
  inuse: true
- id: 20000
  currency: btcd
  fixed: 8
  fee: 0.0005
  inuse: true
- id: 60000
  currency: xrpd
  fixed: 3
  fee: 0.0009
  inuse: true
- id: 80000
  currency: bchd
  fixed: 8
  fee: 0.0005
  inuse: true
- id: 100000
  currency: ltcd
  fixed: 8
  fee: 0.0005
  inuse: true